name: Build, and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Cache Toolchain (${{matrix.toolchain}})
        uses: actions/cache@v2
        env:
          cache-name: cached-cross-compiler
        with:
          path: |
            **/meta/toolchain/${{matrix.toolchain}}/local
          key: |
            v2-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/meta/toolchain/${{matrix.toolchain}}/build.sh') }}
          restore-keys: |
            v2-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/meta/toolchain/${{matrix.toolchain}}/build.sh') }}

      - name: Build Toolchain
        run: |
          meta/toolchain/${{matrix.toolchain}}/build.sh

      - name: Build Kernel
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} all

      - name: Run Tests
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} run-test

      - name: Run BID
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} run-bid

